"""002_add_smtp_whatsapp_tables

Revision ID: 1389870fd761
Revises: b1b5f32abac8
Create Date: 2025-08-22 19:37:20.763990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1389870fd761'
down_revision = 'b1b5f32abac8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_smtp_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('smtp_server', sa.String(length=255), nullable=False),
    sa.Column('smtp_port', sa.Integer(), nullable=False),
    sa.Column('smtp_username', sa.String(length=255), nullable=False),
    sa.Column('smtp_password', sa.Text(), nullable=False),
    sa.Column('smtp_use_tls', sa.Boolean(), nullable=False),
    sa.Column('smtp_use_ssl', sa.Boolean(), nullable=False),
    sa.Column('from_email', sa.String(length=255), nullable=False),
    sa.Column('from_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_smtp_configs_id'), 'customer_smtp_configs', ['id'], unique=False)
    
    op.create_table('customer_whatsapp_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('instance_name', sa.String(length=100), nullable=False),
    sa.Column('evolution_instance_id', sa.String(length=100), nullable=True),
    sa.Column('connection_status', sa.String(length=50), nullable=False),
    sa.Column('qr_code', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_whatsapp_configs_id'), 'customer_whatsapp_configs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_whatsapp_configs_id'), table_name='customer_whatsapp_configs')
    op.drop_table('customer_whatsapp_configs')
    op.drop_index(op.f('ix_customer_smtp_configs_id'), table_name='customer_smtp_configs')
    op.drop_table('customer_smtp_configs')
    # ### end Alembic commands ###