"""add_email_funnels_tables

Revision ID: a98586d0d00c
Revises: c14000459412
Create Date: 2025-08-28 18:14:31.905140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a98586d0d00c'
down_revision = 'c14000459412'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_funnels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('trigger_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('email_subject', sa.String(length=200), nullable=False),
    sa.Column('email_body', sa.Text(), nullable=False),
    sa.Column('email_from_name', sa.String(length=100), nullable=True),
    sa.Column('webhook_endpoint', sa.String(length=500), nullable=True),
    sa.Column('webhook_secret', sa.String(length=100), nullable=True),
    sa.Column('cron_schedule', sa.String(length=50), nullable=True),
    sa.Column('cron_timezone', sa.String(length=50), nullable=True),
    sa.Column('n8n_workflow_id', sa.String(length=100), nullable=True),
    sa.Column('n8n_webhook_id', sa.String(length=100), nullable=True),
    sa.Column('recipient_source', sa.String(length=20), nullable=False),
    sa.Column('recipient_list', sa.JSON(), nullable=True),
    sa.Column('template_variables', sa.JSON(), nullable=True),
    sa.Column('emails_sent', sa.Integer(), nullable=False),
    sa.Column('emails_delivered', sa.Integer(), nullable=False),
    sa.Column('emails_opened', sa.Integer(), nullable=False),
    sa.Column('emails_clicked', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_funnels_id'), 'email_funnels', ['id'], unique=False)
    op.create_table('funnel_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('funnel_id', sa.Integer(), nullable=False),
    sa.Column('recipient_email', sa.String(length=255), nullable=False),
    sa.Column('recipient_data', sa.JSON(), nullable=True),
    sa.Column('execution_type', sa.String(length=20), nullable=True),
    sa.Column('email_subject', sa.String(length=200), nullable=True),
    sa.Column('email_body', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('n8n_execution_id', sa.String(length=100), nullable=True),
    sa.Column('queued_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('clicked_at', sa.DateTime(), nullable=True),
    sa.Column('failed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['funnel_id'], ['email_funnels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funnel_executions_id'), 'funnel_executions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_funnel_executions_id'), table_name='funnel_executions')
    op.drop_table('funnel_executions')
    op.drop_index(op.f('ix_email_funnels_id'), table_name='email_funnels')
    op.drop_table('email_funnels')
    # ### end Alembic commands ###