"""004_add_proj_tbl

Revision ID: c14000459412
Revises: 7908258cd6fe
Create Date: 2025-08-28 13:48:34.230702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c14000459412'
down_revision = '7908258cd6fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.add_column('customer_smtp_configs', sa.Column('project_id', sa.Integer(), nullable=False))
    op.alter_column('customer_smtp_configs', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'customer_smtp_configs', 'projects', ['project_id'], ['id'])
    op.add_column('customer_whatsapp_configs', sa.Column('project_id', sa.Integer(), nullable=False))
    op.alter_column('customer_whatsapp_configs', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'customer_whatsapp_configs', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customer_whatsapp_configs', type_='foreignkey')
    op.alter_column('customer_whatsapp_configs', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('customer_whatsapp_configs', 'project_id')
    op.drop_constraint(None, 'customer_smtp_configs', type_='foreignkey')
    op.alter_column('customer_smtp_configs', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('customer_smtp_configs', 'project_id')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###